/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductionEntry = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'rate' : IDL.Float64,
  'employeeId' : IDL.Text,
  'operationId' : IDL.Text,
  'quantity' : IDL.Nat,
  'bundleId' : IDL.Text,
  'amount' : IDL.Float64,
  'supervisorId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'checkIn' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
  'checkOut' : IDL.Text,
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'dateCreated' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'stage' : IDL.Text,
  'style' : IDL.Text,
  'quantity' : IDL.Nat,
  'priority' : IDL.Text,
  'qrCode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'bankAccount' : IDL.Text,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'aadhaar' : IDL.Text,
  'specialization' : IDL.Text,
  'ratePerPiece' : IDL.Float64,
  'salaryType' : IDL.Text,
  'skillLevel' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'stockQty' : IDL.Nat,
  'unit' : IDL.Text,
  'itemName' : IDL.Text,
});
export const Operation = IDL.Record({
  'id' : IDL.Text,
  'dailyTarget' : IDL.Nat,
  'name' : IDL.Text,
  'ratePerPiece' : IDL.Float64,
  'department' : IDL.Text,
});
export const QualityControl = IDL.Record({
  'id' : IDL.Text,
  'rejectedQty' : IDL.Nat,
  'reworkStatus' : IDL.Text,
  'operationId' : IDL.Text,
  'bundleId' : IDL.Text,
  'reason' : IDL.Text,
});
export const Report = IDL.Record({
  'totalPieces' : IDL.Nat,
  'employeeId' : IDL.Text,
  'totalAmount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkProductionEntries' : IDL.Func([IDL.Vec(ProductionEntry)], [], []),
  'addBundle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'addEmployee' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'addInventoryItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'addOperation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addProductionEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Text],
      [],
    ),
  'addQualityControl' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBundle' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteOperation' : IDL.Func([IDL.Text], [], []),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getBundle' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
  'getBundleByQRCode' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
  'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getEntriesByBundle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getEntriesByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getMonthlyAttendanceByEmployee' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
  'getOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
  'getPerformanceRanking' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'totalPieces' : IDL.Nat, 'employeeId' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'getProductionEntries' : IDL.Func([], [IDL.Vec(ProductionEntry)], ['query']),
  'getProductionSummaryForToday' : IDL.Func(
      [],
      [IDL.Nat, IDL.Float64],
      ['query'],
    ),
  'getQualityControl' : IDL.Func([], [IDL.Vec(QualityControl)], ['query']),
  'getSalarySheet' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueInventoryToBundle' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBundle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateOperation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductionEntry = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'rate' : IDL.Float64,
    'employeeId' : IDL.Text,
    'operationId' : IDL.Text,
    'quantity' : IDL.Nat,
    'bundleId' : IDL.Text,
    'amount' : IDL.Float64,
    'supervisorId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'checkIn' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
    'checkOut' : IDL.Text,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'dateCreated' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'stage' : IDL.Text,
    'style' : IDL.Text,
    'quantity' : IDL.Nat,
    'priority' : IDL.Text,
    'qrCode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'bankAccount' : IDL.Text,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'aadhaar' : IDL.Text,
    'specialization' : IDL.Text,
    'ratePerPiece' : IDL.Float64,
    'salaryType' : IDL.Text,
    'skillLevel' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'stockQty' : IDL.Nat,
    'unit' : IDL.Text,
    'itemName' : IDL.Text,
  });
  const Operation = IDL.Record({
    'id' : IDL.Text,
    'dailyTarget' : IDL.Nat,
    'name' : IDL.Text,
    'ratePerPiece' : IDL.Float64,
    'department' : IDL.Text,
  });
  const QualityControl = IDL.Record({
    'id' : IDL.Text,
    'rejectedQty' : IDL.Nat,
    'reworkStatus' : IDL.Text,
    'operationId' : IDL.Text,
    'bundleId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Report = IDL.Record({
    'totalPieces' : IDL.Nat,
    'employeeId' : IDL.Text,
    'totalAmount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkProductionEntries' : IDL.Func([IDL.Vec(ProductionEntry)], [], []),
    'addBundle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addEmployee' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addOperation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addProductionEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Text],
        [],
      ),
    'addQualityControl' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBundle' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteOperation' : IDL.Func([IDL.Text], [], []),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getBundle' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
    'getBundleByQRCode' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
    'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getEntriesByBundle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getEntriesByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getMonthlyAttendanceByEmployee' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
    'getOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
    'getPerformanceRanking' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'totalPieces' : IDL.Nat, 'employeeId' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getProductionEntries' : IDL.Func(
        [],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionSummaryForToday' : IDL.Func(
        [],
        [IDL.Nat, IDL.Float64],
        ['query'],
      ),
    'getQualityControl' : IDL.Func([], [IDL.Vec(QualityControl)], ['query']),
    'getSalarySheet' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueInventoryToBundle' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBundle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateOperation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };