/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : string,
  'date' : string,
  'employeeId' : string,
}
export interface Bundle {
  'id' : string,
  'status' : string,
  'styleNumber' : string,
  'color' : string,
  'size' : string,
  'createdDate' : string,
  'quantity' : bigint,
}
export interface DashboardStats {
  'todayProduction' : bigint,
  'runningBundlesCount' : bigint,
}
export interface Employee {
  'id' : string,
  'status' : string,
  'joinDate' : string,
  'name' : string,
  'salaryType' : string,
  'phone' : string,
  'department' : string,
}
export interface Operation {
  'id' : string,
  'dailyTarget' : bigint,
  'name' : string,
  'ratePerPiece' : number,
  'department' : string,
}
export interface ProductionEntry {
  'id' : string,
  'date' : string,
  'rate' : number,
  'employeeId' : string,
  'operationId' : string,
  'quantity' : bigint,
  'bundleId' : string,
  'amount' : number,
}
export interface Target {
  'id' : string,
  'date' : string,
  'targetQty' : bigint,
  'operationId' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBundle' : ActorMethod<
    [string, string, string, bigint, string, string],
    string
  >,
  'addEmployee' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'addOperation' : ActorMethod<[string, number, string, bigint], string>,
  'addProductionEntry' : ActorMethod<
    [string, string, string, string, bigint, number, number],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBundle' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteOperation' : ActorMethod<[string], undefined>,
  'getAllAttendance' : ActorMethod<[], Array<Attendance>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<Attendance>>,
  'getBundle' : ActorMethod<[string], [] | [Bundle]>,
  'getBundleProgress' : ActorMethod<
    [string],
    Array<{ 'completed' : boolean, 'operationId' : string }>
  >,
  'getBundles' : ActorMethod<[], Array<Bundle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getEntriesByDate' : ActorMethod<[string], Array<ProductionEntry>>,
  'getEntriesByEmployee' : ActorMethod<[string], Array<ProductionEntry>>,
  'getEntriesByMonth' : ActorMethod<[bigint, bigint], Array<ProductionEntry>>,
  'getMonthlySalary' : ActorMethod<
    [bigint, bigint],
    Array<
      { 'totalPieces' : bigint, 'employeeId' : string, 'totalAmount' : number }
    >
  >,
  'getOperation' : ActorMethod<[string], [] | [Operation]>,
  'getOperations' : ActorMethod<[], Array<Operation>>,
  'getOperatorRankingToday' : ActorMethod<
    [string],
    Array<{ 'totalQty' : bigint, 'employeeId' : string }>
  >,
  'getProductionEntries' : ActorMethod<[], Array<ProductionEntry>>,
  'getTargets' : ActorMethod<[], Array<Target>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTarget' : ActorMethod<[string, bigint, string], string>,
  'updateAttendance' : ActorMethod<[string, string, string, string], undefined>,
  'updateBundle' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    undefined
  >,
  'updateEmployee' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateOperation' : ActorMethod<
    [string, string, number, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];