/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'styleNumber' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'createdDate' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const DashboardStats = IDL.Record({
  'todayProduction' : IDL.Nat,
  'runningBundlesCount' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'salaryType' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const ProductionEntry = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'rate' : IDL.Float64,
  'employeeId' : IDL.Text,
  'operationId' : IDL.Text,
  'quantity' : IDL.Nat,
  'bundleId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Operation = IDL.Record({
  'id' : IDL.Text,
  'dailyTarget' : IDL.Nat,
  'name' : IDL.Text,
  'ratePerPiece' : IDL.Float64,
  'department' : IDL.Text,
});
export const Target = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'targetQty' : IDL.Nat,
  'operationId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBundle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addOperation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addProductionEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBundle' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteOperation' : IDL.Func([IDL.Text], [], []),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getBundle' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
  'getBundleProgress' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({ 'completed' : IDL.Bool, 'operationId' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getEntriesByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getEntriesByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getMonthlySalary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'totalPieces' : IDL.Nat,
            'employeeId' : IDL.Text,
            'totalAmount' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
  'getOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
  'getOperatorRankingToday' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({ 'totalQty' : IDL.Nat, 'employeeId' : IDL.Text }))],
      ['query'],
    ),
  'getProductionEntries' : IDL.Func([], [IDL.Vec(ProductionEntry)], ['query']),
  'getTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTarget' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'updateAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBundle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOperation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'styleNumber' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'createdDate' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const DashboardStats = IDL.Record({
    'todayProduction' : IDL.Nat,
    'runningBundlesCount' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'salaryType' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const ProductionEntry = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'rate' : IDL.Float64,
    'employeeId' : IDL.Text,
    'operationId' : IDL.Text,
    'quantity' : IDL.Nat,
    'bundleId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Operation = IDL.Record({
    'id' : IDL.Text,
    'dailyTarget' : IDL.Nat,
    'name' : IDL.Text,
    'ratePerPiece' : IDL.Float64,
    'department' : IDL.Text,
  });
  const Target = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'targetQty' : IDL.Nat,
    'operationId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBundle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addOperation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addProductionEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBundle' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteOperation' : IDL.Func([IDL.Text], [], []),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getBundle' : IDL.Func([IDL.Text], [IDL.Opt(Bundle)], ['query']),
    'getBundleProgress' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({ 'completed' : IDL.Bool, 'operationId' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getEntriesByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getEntriesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getMonthlySalary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'totalPieces' : IDL.Nat,
              'employeeId' : IDL.Text,
              'totalAmount' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
    'getOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
    'getOperatorRankingToday' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({ 'totalQty' : IDL.Nat, 'employeeId' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getProductionEntries' : IDL.Func(
        [],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTarget' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'updateAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBundle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOperation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };