/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : string,
  'checkIn' : string,
  'date' : string,
  'employeeId' : string,
  'checkOut' : string,
}
export interface Bundle {
  'id' : string,
  'status' : string,
  'dateCreated' : string,
  'color' : string,
  'size' : string,
  'stage' : string,
  'style' : string,
  'quantity' : bigint,
  'priority' : string,
  'qrCode' : string,
}
export interface Employee {
  'id' : string,
  'status' : string,
  'bankAccount' : string,
  'joinDate' : string,
  'name' : string,
  'aadhaar' : string,
  'specialization' : string,
  'ratePerPiece' : number,
  'salaryType' : string,
  'skillLevel' : string,
  'phone' : string,
  'department' : string,
}
export interface InventoryItem {
  'id' : string,
  'stockQty' : bigint,
  'unit' : string,
  'itemName' : string,
}
export interface Operation {
  'id' : string,
  'dailyTarget' : bigint,
  'name' : string,
  'ratePerPiece' : number,
  'department' : string,
}
export interface ProductionEntry {
  'id' : string,
  'date' : string,
  'rate' : number,
  'employeeId' : string,
  'operationId' : string,
  'quantity' : bigint,
  'bundleId' : string,
  'amount' : number,
  'supervisorId' : string,
}
export interface QualityControl {
  'id' : string,
  'rejectedQty' : bigint,
  'reworkStatus' : string,
  'operationId' : string,
  'bundleId' : string,
  'reason' : string,
}
export interface Report {
  'totalPieces' : bigint,
  'employeeId' : string,
  'totalAmount' : number,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBulkProductionEntries' : ActorMethod<[Array<ProductionEntry>], undefined>,
  'addBundle' : ActorMethod<
    [string, string, string, bigint, string, string, string, string],
    string
  >,
  'addEmployee' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    string
  >,
  'addInventoryItem' : ActorMethod<[string, bigint, string], string>,
  'addOperation' : ActorMethod<[string, string, number, bigint], string>,
  'addProductionEntry' : ActorMethod<
    [string, string, string, string, string, bigint, number, number],
    string
  >,
  'addQualityControl' : ActorMethod<
    [string, string, bigint, string, string],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBundle' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteOperation' : ActorMethod<[string], undefined>,
  'getAttendanceByDate' : ActorMethod<[string], Array<Attendance>>,
  'getBundle' : ActorMethod<[string], [] | [Bundle]>,
  'getBundleByQRCode' : ActorMethod<[string], [] | [Bundle]>,
  'getBundles' : ActorMethod<[], Array<Bundle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getEntriesByBundle' : ActorMethod<[string], Array<ProductionEntry>>,
  'getEntriesByDate' : ActorMethod<[string], Array<ProductionEntry>>,
  'getEntriesByEmployee' : ActorMethod<[string], Array<ProductionEntry>>,
  'getInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getMonthlyAttendanceByEmployee' : ActorMethod<
    [string, bigint, bigint],
    Array<Attendance>
  >,
  'getOperation' : ActorMethod<[string], [] | [Operation]>,
  'getOperations' : ActorMethod<[], Array<Operation>>,
  'getPerformanceRanking' : ActorMethod<
    [],
    Array<{ 'totalPieces' : bigint, 'employeeId' : string }>
  >,
  'getProductionEntries' : ActorMethod<[], Array<ProductionEntry>>,
  'getProductionSummaryForToday' : ActorMethod<[], [bigint, number]>,
  'getQualityControl' : ActorMethod<[], Array<QualityControl>>,
  'getSalarySheet' : ActorMethod<[bigint, bigint], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueInventoryToBundle' : ActorMethod<[string, bigint], undefined>,
  'markAttendance' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAttendance' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateBundle' : ActorMethod<
    [string, string, string, string, bigint, string, string, string, string],
    undefined
  >,
  'updateEmployee' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateInventoryItem' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
  'updateOperation' : ActorMethod<
    [string, string, string, number, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];